package user

import "C"

import "factory/cgoFile/ext"

// CgoBypass is in a file that imports "C", so go vet type-checks cmd/cgo's
// rewritten copy of it instead of this source, and that copy's own
// "Code generated by cmd/cgo" header must not hide this bypass. This file
// only builds where cgo is enabled, so without a C compiler it is excluded
// from this package the same way a build-tag mismatch would be, as it is
// in this sandbox; the case only bites in an environment that has one.
func CgoBypass() {
	_ = ext.Struct{} // want `Use factory for ext.Struct \(ext.NewStruct\)`
}
