package user

import "C"

import "factory/cgoFile/ext"

// CgoBypass is in a file that imports "C", so go vet type-checks cmd/cgo's
// rewritten copy of it instead of this source, and that copy's own
// "Code generated by cmd/cgo" header must not hide this bypass.
func CgoBypass() {
	_ = ext.Struct{} // want `Use factory for ext.Struct \(ext.NewStruct\)`
}
