version: "2"
linters:
  default: all
  disable:
    - depguard
    - exhaustruct
    - thelper
    - wsl
  settings:
    dupl:
      threshold: 100
    lll:
      line-length: 80
    varnamelen:
      ignore-names:
        - v
        - ok
    funcorder:
      constructor: true
      struct-method: false
      alphabetical: false
      function: false
  exclusions:
    generated: lax
    rules:
      - linters:
          - varnamelen
          - wrapcheck
        path: lint_test
      - linters:
          - lll
        source: "^(?: |\t)*// "
      - linters:
          - lll
        source: '[`"''].*[`"'']'
      - linters:
          - godot
          - lll
        source: '// ?TODO '
    paths:
      - testdata
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - testdata
      - third_party$
      - builtin$
      - examples$
