package gofactory

import (
	"go/ast"
	"go/types"
	"regexp"
	"slices"
	"strings"

	"github.com/gobwas/glob"
	"golang.org/x/tools/go/analysis"
)

// detector resolves bypass routes through the type checker instead of
// syntax, so a literal, conversion, new(T), implicit constant conversion
// or, with -zeroValues, a zero value of a protected type is reported however
// it is spelled.
type detector struct {
	pass        *analysis.Pass
	strategy    blockedStrategy
	ignoreTypes []glob.Glob
	zeroValues  bool

	factoryPatterns []*regexp.Regexp
	onlyWithFactory bool

	factories map[*types.Package]factoryIndex
	declared  factoryIndex
	suffixes  map[*types.TypeName]string

	fieldPathCache map[types.Type][]fieldPath

	locallyIgnored map[types.Object]bool

	// The test main go test synthesizes carries the
	// "// Code generated ... DO NOT EDIT." header too.
	generatedFiles map[*ast.File]bool

	// currentFn is the FuncDecl enclosing the checked node, nil at package
	// scope; a closure counts as its enclosing FuncDecl.
	currentFn *types.Func
}

func newDetector(
	pass *analysis.Pass,
	strategy blockedStrategy,
	ignoreTypes []glob.Glob,
	zeroValues bool,
	factoryPatterns []*regexp.Regexp,
	onlyWithFactory bool,
	declared factoryIndex,
	locallyIgnored map[types.Object]bool,
) *detector {
	generatedFiles := map[*ast.File]bool{}

	for _, file := range pass.Files {
		if isGenerated(file) {
			generatedFiles[file] = true
		}
	}

	return &detector{
		pass:            pass,
		strategy:        strategy,
		ignoreTypes:     ignoreTypes,
		zeroValues:      zeroValues,
		factoryPatterns: factoryPatterns,
		onlyWithFactory: onlyWithFactory,
		factories:       map[*types.Package]factoryIndex{},
		declared:        declared,
		suffixes:        map[*types.TypeName]string{},
		fieldPathCache:  map[types.Type][]fieldPath{},
		locallyIgnored:  locallyIgnored,
		generatedFiles:  generatedFiles,
	}
}

// generatedByCgo is the name generatedBy extracts from cmd/cgo's header,
// "// Code generated by cmd/cgo; DO NOT EDIT.".
const generatedByCgo = "by cmd/cgo;"

// isGenerated is go/ast.IsGenerated, except that cmd/cgo's header is only
// treated as marking a copy of a source file when a //line directive
// comment immediately follows it (cmd/cgo/out.go:707,713): that directive
// is what cmd/cgo writes ahead of the source it copied, and the
// copied file's own header, if it has one, follows the directive in
// turn, so scanning continues there instead of stopping. Without a
// following //line directive, the header belongs to a file cmd/cgo wrote
// entirely by itself, such as _cgo_gotypes.go (out.go:82), and that file
// is generated.
func isGenerated(file *ast.File) bool {
	comments := flattenComments(file)

	for idx, comment := range comments {
		if comment.Pos() > file.Package {
			return false
		}

		gen, ok := generatedBy(comment.Text)
		if !ok {
			continue
		}

		if gen == generatedByCgo && isLineDirective(comments, idx+1) {
			continue
		}

		return true
	}

	return false
}

func flattenComments(file *ast.File) []*ast.Comment {
	var comments []*ast.Comment

	for _, group := range file.Comments {
		comments = append(comments, group.List...)
	}

	return comments
}

func isLineDirective(comments []*ast.Comment, idx int) bool {
	return idx < len(comments) && strings.HasPrefix(comments[idx].Text, "//line ")
}

func generatedBy(text string) (string, bool) {
	const prefix = "// Code generated "

	if !strings.Contains(text, prefix) {
		return "", false
	}

	for line := range strings.SplitSeq(text, "\n") {
		rest, ok := strings.CutPrefix(line, prefix)
		if !ok {
			continue
		}

		if gen, ok := strings.CutSuffix(rest, " DO NOT EDIT."); ok {
			return gen, true
		}
	}

	return "", false
}

func (d *detector) visit(node ast.Node, push bool, stack []ast.Node) bool {
	if !push {
		return true
	}

	if file, ok := stack[0].(*ast.File); ok && d.generatedFiles[file] {
		return false
	}

	d.currentFn = d.topLevelFunc(stack)
	d.check(node)

	return true
}

func (d *detector) check(node ast.Node) {
	switch node := node.(type) {
	case *ast.CompositeLit:
		d.checkLiteral(node)
		d.checkElementConstants(node)
	case *ast.CallExpr:
		d.checkCall(node)
		d.checkArgConstants(node)
	case *ast.GenDecl:
		d.checkVarConstants(node)
	case *ast.AssignStmt:
		d.checkAssignedConstants(node)
	case *ast.ReturnStmt:
		d.checkStoredConstants(node.Results)
	case *ast.FuncDecl:
		d.checkFuncZeroValues(node.Type, node.Body)
	case *ast.FuncLit:
		d.checkFuncZeroValues(node.Type, node.Body)
	}
}

// stack[0] is the *ast.File, so stack[1] is the top-level declaration
// holding the visited node.
func (d *detector) topLevelFunc(stack []ast.Node) *types.Func {
	decl, ok := stack[1].(*ast.FuncDecl)
	if !ok {
		return nil
	}

	fn, _ := d.pass.TypesInfo.ObjectOf(decl.Name).(*types.Func)

	return fn
}

func (d *detector) reportProtected(node ast.Node, t types.Type) {
	d.reportProtectedSuffix(node, t, "")
}

// Every bypass route reports through here, so the permission policy is
// applied in one place; visit and checkPackageVars drop generated files
// before any route runs.
func (d *detector) reportProtectedSuffix(
	node ast.Node, t types.Type, suffix string,
) {
	named, ok := protectedNamed(t)
	if !ok || d.isIgnored(named) {
		return
	}

	if slices.Contains(d.declared[named.Obj()], d.currentFn) {
		return
	}

	if !d.strategy.IsBlocked(d.pass.Pkg, named.Obj(), d.currentFn) {
		return
	}

	d.report(node, named, suffix)
}

func (d *detector) isIgnored(named *types.Named) bool {
	obj := named.Obj()

	if d.locallyIgnored[obj] {
		return true
	}

	var fact ignoredFact
	if d.pass.ImportObjectFact(obj, &fact) {
		return true
	}

	name := obj.Pkg().Path() + "." + obj.Name()

	return matchesAnyGlob(d.ignoreTypes, name)
}

func (d *detector) report(pos ast.Node, named *types.Named, route string) {
	obj := named.Obj()

	factory := d.factorySuffix(obj)
	if d.onlyWithFactory && factory == "" {
		return
	}

	d.pass.Reportf(
		pos.Pos(),
		"Use factory for %s.%s%s%s", obj.Pkg().Name(), obj.Name(),
		route, factory,
	)
}

func (d *detector) factorySuffix(target *types.TypeName) string {
	if suffix, ok := d.suffixes[target]; ok {
		return suffix
	}

	index, ok := d.factories[target.Pkg()]
	if !ok {
		index = indexFactories(target.Pkg(), d.factoryPatterns)
		d.factories[target.Pkg()] = index
	}

	// A recognised factory may also be declared; skip adding it twice.
	factories := append([]*types.Func{}, index[target]...)
	for _, fn := range d.declared[target] {
		if !slices.Contains(factories, fn) {
			factories = append(factories, fn)
		}
	}

	suffix := factorySuffix(d.pass.Pkg, factories)
	d.suffixes[target] = suffix

	return suffix
}
