package gofactory

import (
	"go/ast"
	"go/types"
	"regexp"
	"slices"
	"strings"

	"github.com/gobwas/glob"
	"golang.org/x/tools/go/analysis"
)

// detector resolves bypass routes through the type checker instead of
// syntax, so a literal, conversion, new(T) or, with -zeroValues, a zero
// value of a protected type is reported however it is spelled.
type detector struct {
	pass        *analysis.Pass
	strategy    blockedStrategy
	ignoreTypes []glob.Glob
	zeroValues  bool

	factoryPatterns []*regexp.Regexp
	onlyWithFactory bool

	factories map[*types.Package]factoryIndex
	declared  factoryIndex
	suffixes  map[*types.TypeName]string

	fieldPathCache map[types.Type][]fieldPath

	locallyIgnored map[types.Object]bool

	// The test main go test synthesizes carries this header too.
	generatedFiles map[*ast.File]bool

	// currentFn is the FuncDecl enclosing the checked node, nil at package
	// scope; a closure counts as its enclosing FuncDecl.
	currentFn *types.Func
}

func newDetector(
	pass *analysis.Pass,
	strategy blockedStrategy,
	ignoreTypes []glob.Glob,
	zeroValues bool,
	factoryPatterns []*regexp.Regexp,
	onlyWithFactory bool,
	declared factoryIndex,
	locallyIgnored map[types.Object]bool,
) *detector {
	generatedFiles := map[*ast.File]bool{}

	for _, file := range pass.Files {
		if isGenerated(file) {
			generatedFiles[file] = true
		}
	}

	return &detector{
		pass:            pass,
		strategy:        strategy,
		ignoreTypes:     ignoreTypes,
		zeroValues:      zeroValues,
		factoryPatterns: factoryPatterns,
		onlyWithFactory: onlyWithFactory,
		factories:       map[*types.Package]factoryIndex{},
		declared:        declared,
		suffixes:        map[*types.TypeName]string{},
		fieldPathCache:  map[types.Type][]fieldPath{},
		locallyIgnored:  locallyIgnored,
		generatedFiles:  generatedFiles,
	}
}

// generatedByCgo is the text generatedBy returns for the header cmd/cgo
// writes, ahead of a //line directive, into its compiled copy of every
// file that imports "C" (cmd/cgo/out.go writes
// "// Code generated by cmd/cgo; DO NOT EDIT."). go/packages hands the type
// checker that copy in place of the handwritten file, so go/ast.IsGenerated
// would call every such file generated on this header alone, hiding any
// bypass the author actually wrote there.
const generatedByCgo = "by cmd/cgo;"

// isGenerated is go/ast.IsGenerated, except that a first match naming
// cmd/cgo as generator is not enough by itself: the handwritten file behind
// it keeps its own header, if it has one, right after the //line directive,
// so scanning continues into the comments that follow instead of stopping
// there. A genuinely generated cgo file is still caught through that
// surviving header.
func isGenerated(file *ast.File) bool {
	skippedCgoHeader := false

	for _, group := range file.Comments {
		for _, comment := range group.List {
			if comment.Pos() > file.Package {
				return false
			}

			gen, ok := generatedBy(comment.Text)
			if !ok {
				continue
			}

			if gen == generatedByCgo && !skippedCgoHeader {
				skippedCgoHeader = true

				continue
			}

			return true
		}
	}

	return false
}

// generatedBy extracts the generator name from a single comment's text, in
// the form go/ast.IsGenerated recognises: "// Code generated <name> DO NOT
// EDIT.".
func generatedBy(text string) (string, bool) {
	const prefix = "// Code generated "

	if !strings.Contains(text, prefix) {
		return "", false
	}

	for line := range strings.SplitSeq(text, "\n") {
		rest, ok := strings.CutPrefix(line, prefix)
		if !ok {
			continue
		}

		if gen, ok := strings.CutSuffix(rest, " DO NOT EDIT."); ok {
			return gen, true
		}
	}

	return "", false
}

func (d *detector) visit(node ast.Node, push bool, stack []ast.Node) bool {
	if !push {
		return true
	}

	if file, ok := stack[0].(*ast.File); ok && d.generatedFiles[file] {
		return false
	}

	d.currentFn = d.topLevelFunc(stack)

	switch node := node.(type) {
	case *ast.CompositeLit:
		d.checkLiteral(node)
	case *ast.CallExpr:
		d.checkCall(node)
	case *ast.FuncDecl:
		d.checkFuncZeroValues(node.Type, node.Body)
	case *ast.FuncLit:
		d.checkFuncZeroValues(node.Type, node.Body)
	}

	return true
}

// stack[0] is the *ast.File, so stack[1] is the top-level declaration
// holding the visited node.
func (d *detector) topLevelFunc(stack []ast.Node) *types.Func {
	decl, ok := stack[1].(*ast.FuncDecl)
	if !ok {
		return nil
	}

	fn, _ := d.pass.TypesInfo.ObjectOf(decl.Name).(*types.Func)

	return fn
}

func (d *detector) reportProtected(node ast.Node, t types.Type) {
	d.reportProtectedSuffix(node, t, "")
}

// Every bypass route reports through here, so the permission policy is
// applied in one place.
func (d *detector) reportProtectedSuffix(
	node ast.Node, t types.Type, suffix string,
) {
	named, ok := protectedNamed(t)
	if !ok || d.isIgnored(named) {
		return
	}

	if slices.Contains(d.declared[named.Obj()], d.currentFn) {
		return
	}

	if !d.strategy.IsBlocked(d.pass.Pkg, named.Obj(), d.currentFn) {
		return
	}

	d.report(node, named, suffix)
}

func (d *detector) isIgnored(named *types.Named) bool {
	obj := named.Obj()

	if d.locallyIgnored[obj] {
		return true
	}

	var fact ignoredFact
	if d.pass.ImportObjectFact(obj, &fact) {
		return true
	}

	name := obj.Pkg().Path() + "." + obj.Name()

	return matchesAnyGlob(d.ignoreTypes, name)
}

func (d *detector) report(pos ast.Node, named *types.Named, route string) {
	obj := named.Obj()

	factory := d.factorySuffix(obj)
	if d.onlyWithFactory && factory == "" {
		return
	}

	d.pass.Reportf(
		pos.Pos(),
		"Use factory for %s.%s%s%s", obj.Pkg().Name(), obj.Name(),
		route, factory,
	)
}

func (d *detector) factorySuffix(target *types.TypeName) string {
	if suffix, ok := d.suffixes[target]; ok {
		return suffix
	}

	index, ok := d.factories[target.Pkg()]
	if !ok {
		index = indexFactories(target.Pkg(), d.factoryPatterns)
		d.factories[target.Pkg()] = index
	}

	// A recognised factory may also be declared; skip adding it twice.
	factories := append([]*types.Func{}, index[target]...)
	for _, fn := range d.declared[target] {
		if !slices.Contains(factories, fn) {
			factories = append(factories, fn)
		}
	}

	suffix := factorySuffix(d.pass.Pkg, factories)
	d.suffixes[target] = suffix

	return suffix
}
