package gofactory

import (
	"go/ast"
	"strings"
)

// generatedByCgo is the name generatedBy extracts from cmd/cgo's header,
// "// Code generated by cmd/cgo; DO NOT EDIT.".
const generatedByCgo = "by cmd/cgo;"

// isGenerated is go/ast.IsGenerated, except that cmd/cgo's header is only
// treated as marking a copy of a source file when a //line directive
// comment immediately follows it (writeOutput in cmd/cgo/out.go): that
// directive is what cmd/cgo writes ahead of the source it copied, and the
// copied file's own header, if it has one, follows the directive in turn,
// so scanning continues there instead of stopping. Without a following
// //line directive, the header belongs to a file cmd/cgo wrote entirely by
// itself, such as _cgo_gotypes.go (writeDefs in cmd/cgo/out.go), and that
// file is generated.
func isGenerated(file *ast.File) bool {
	comments := flattenComments(file)

	for idx, comment := range comments {
		if comment.Pos() > file.Package {
			return false
		}

		gen, ok := generatedBy(comment.Text)
		if !ok {
			continue
		}

		if gen == generatedByCgo && isLineDirective(comments, idx+1) {
			continue
		}

		return true
	}

	return false
}

func flattenComments(file *ast.File) []*ast.Comment {
	var comments []*ast.Comment

	for _, group := range file.Comments {
		comments = append(comments, group.List...)
	}

	return comments
}

func isLineDirective(comments []*ast.Comment, idx int) bool {
	return idx < len(comments) && strings.HasPrefix(comments[idx].Text, "//line ")
}

func generatedBy(text string) (string, bool) {
	const prefix = "// Code generated "

	if !strings.Contains(text, prefix) {
		return "", false
	}

	for line := range strings.SplitSeq(text, "\n") {
		rest, ok := strings.CutPrefix(line, prefix)
		if !ok {
			continue
		}

		if gen, ok := strings.CutSuffix(rest, " DO NOT EDIT."); ok {
			return gen, true
		}
	}

	return "", false
}
