// Code generated by cmd/cgo; DO NOT EDIT.

//line cgocopy.go:4:1
package user

import "factory/generatedFiles/ext"

func CgoCopyBypass() {
	_ = ext.Struct{} // want `Use factory for ext.Struct \(ext.NewStruct\)`
}
