// Code generated by cmd/cgo; DO NOT EDIT.

package user

import "factory/generatedFiles/ext"

//go:noinline
func CgoGotypesBypass() {
	// The directive above stands in for the //go:linkname lines that follow
	// cmd/cgo's header in a real _cgo_gotypes.go: a comment there that is not
	// //line must not make this file count as cmd/cgo's copy of a source file.
	_ = ext.Struct{}
}
