// Code generated by cmd/cgo; DO NOT EDIT.

//line cgogenerated.go:4:1
// Code generated by mockgen. DO NOT EDIT.

package user

import "factory/generatedFiles/ext"

func CgoGeneratedBypass() {
	_ = ext.Struct{}
}
