// Code generated by mockgen. DO NOT EDIT.

package user

import "factory/generatedFiles/ext"

func GeneratedBypass() {
	_ = ext.Struct{}
}

var GeneratedZero ext.Struct

func GeneratedRoutes() {
	_ = ext.Struct(struct{}{})
	_ = new(ext.Struct)

	var local ext.Struct

	_ = local
}

//gofactory:bogus // want `unknown directive "//gofactory:bogus"`
type GeneratedDirective struct{}
